version: '3'

tasks:
  install:
    - go install github.com/bokwoon95/wgo@latest
    - go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest
    - go mod download
  build: go build ./src
  tidy: go mod tidy
  run: go run ./src
  watch: wgo run ./src
  test: go test -json -v ./... 2>&1 | gotestfmt